### ISSUE TITLE
认领 视图和web

### ISSUE THREAD

**Issue by abel-oye** [adonis-china/docs#18]
Nunjucks模板
表单生成器

交互式Shell Aka Ace
认证
Cookies
Mail
错误和异常处理
事件

**Comment by wxs77577** [comment]
通过！加油！

**Comment by wxs77577** [comment]
@river-lee `交互式Shell Aka Ace` 已完成一部分，请拉取最新代码后再操作

**Comment by abel-oye** [comment]
ok
